/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/client-message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Client Msg */
    post: operations['client_msg_client_message_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/server-message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Server Msg */
    post: operations['server_msg_server_message_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/payloads/send-message': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** P1 */
    post: operations['p1_payloads_send_message_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AckDeleteMessagePayload */
    AckDeleteMessagePayload: {
      /** Id */
      id: string;
      /** Deletedat */
      deletedAt: string;
    };
    /** AckEditMessagePayload */
    AckEditMessagePayload: {
      /** Id */
      id: string;
      /** Editedat */
      editedAt: string;
    };
    /** AckSendMessagePayload */
    AckSendMessagePayload: {
      /** Id */
      id: string;
      /** Servertimestamp */
      serverTimestamp: string;
    };
    /** ErrorPayload */
    ErrorPayload: {
      /** Message */
      message: string;
    };
    /** MessageStatusBroadcastPayload */
    MessageStatusBroadcastPayload: {
      /** Messageid */
      messageId: string;
      /** Status */
      status: string;
    };
    /** PresenceBroadcastPayload */
    PresenceBroadcastPayload: {
      /** Userid */
      userId: string;
      /** Status */
      status: string;
    };
    /** ReceiveDeleteMessagePayload */
    ReceiveDeleteMessagePayload: {
      /** Id */
      id: string;
      /** Deletetype */
      deleteType: string;
      /** Deletedat */
      deletedAt?: string | null;
    };
    /** ReceiveEditMessagePayload */
    ReceiveEditMessagePayload: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /** Editedat */
      editedAt?: string | null;
    };
    /** ReceiveMessagePayload */
    ReceiveMessagePayload: {
      /** Id */
      id: string;
      /** Chatid */
      chatId: string;
      /** Text */
      text: string;
      /** Senderid */
      senderId: string;
      /** Createdat */
      createdAt: string;
      /** Servertimestamp */
      serverTimestamp: string;
      /** Isdeletedforeveryone */
      isDeletedForEveryone: boolean;
    };
    /** SendMessagePayload */
    SendMessagePayload: {
      /** Chatid */
      chatId: number;
      /** Text */
      text: string;
      /** Id */
      id: number | string;
    };
    /** TypingBroadcastPayload */
    TypingBroadcastPayload: {
      /** Chatid */
      chatId: string;
      /** Userid */
      userId: string;
      /** Istyping */
      isTyping: boolean;
    };
    /** WsClientMessage */
    WsClientMessage: {
      /** Type */
      type: string;
      /** Payload */
      payload: unknown;
      /** Timestamp */
      timestamp?: number | string | null;
    };
    /** WsServerMessage */
    WsServerMessage: {
      /**
       * Event
       * @enum {string}
       */
      event:
        | 'ACK_SEND_MSG'
        | 'RECEIVE_MSG'
        | 'TYPING'
        | 'MSG_STATUS'
        | 'PRESENCE'
        | 'ACK_EDIT_MSG'
        | 'RECEIVE_EDIT_MSG'
        | 'ACK_DELETE_MSG'
        | 'RECEIVE_DELETE_MSG'
        | 'ERROR';
      /** Payload */
      payload:
        | components['schemas']['AckSendMessagePayload']
        | components['schemas']['ReceiveMessagePayload']
        | components['schemas']['TypingBroadcastPayload']
        | components['schemas']['MessageStatusBroadcastPayload']
        | components['schemas']['PresenceBroadcastPayload']
        | components['schemas']['AckEditMessagePayload']
        | components['schemas']['ReceiveEditMessagePayload']
        | components['schemas']['AckDeleteMessagePayload']
        | components['schemas']['ReceiveDeleteMessagePayload']
        | components['schemas']['ErrorPayload'];
      /** Timestamp */
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  client_msg_client_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WsClientMessage'];
        };
      };
    };
  };
  server_msg_server_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WsServerMessage'];
        };
      };
    };
  };
  p1_payloads_send_message_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SendMessagePayload'];
        };
      };
    };
  };
}
