/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** DeleteMessagePayload */
    DeleteMessagePayload: {
      /** Id */
      id: number | string;
      /**
       * Deletetype
       * @enum {string}
       */
      deleteType: 'deleteForMe' | 'deleteForEveryone' | 'both';
      /**
       * Deletedforeveryoneat
       * @default null
       */
      deletedForEveryoneAt: number | string | null;
      /**
       * Deletedformeat
       * @default null
       */
      deletedForMeAt: number | string | null;
    };
    /** EditMessagePayload */
    EditMessagePayload: {
      /** Id */
      id: number | string;
      /** Text */
      text: string;
      /**
       * Editedat
       * @default null
       */
      editedAt: number | string | null;
    };
    /** MessageStatusPayload */
    MessageStatusPayload: {
      /** Messageid */
      messageId: number | string;
      /**
       * Status
       * @enum {string}
       */
      status: 'read' | 'delivered';
    };
    /** PresencePayload */
    PresencePayload: {
      /**
       * Status
       * @enum {string}
       */
      status: 'online' | 'offline';
    };
    /** SendMessagePayload */
    SendMessagePayload: {
      /** Chatid */
      chatId: number;
      /** Text */
      text: string;
      /** Id */
      id: number | string;
    };
    /** TypingPayload */
    TypingPayload: {
      /** Chatid */
      chatId: number;
      /** Istyping */
      isTyping: boolean;
    };
    /** AckDeleteMessagePayload */
    AckDeleteMessagePayload: {
      /** Id */
      id: string;
      /**
       * Deletetype
       * @enum {string}
       */
      deleteType: 'deleteForMe' | 'deleteForEveryone' | 'both';
    };
    /** AckEditMessagePayload */
    AckEditMessagePayload: {
      /** Id */
      id: string;
      /** Editedat */
      editedAt: string;
    };
    /** AckSendMessagePayload */
    AckSendMessagePayload: {
      /** Id */
      id: string;
      /** Servertimestamp */
      serverTimestamp: string;
    };
    /** ErrorPayload */
    ErrorPayload: {
      /** Message */
      message: string;
    };
    /** MessageStatusBroadcastPayload */
    MessageStatusBroadcastPayload: {
      /** Messageid */
      messageId: string;
      /** Status */
      status: string;
    };
    /** PresenceBroadcastPayload */
    PresenceBroadcastPayload: {
      /** Userid */
      userId: string;
      /** Status */
      status: string;
    };
    /** ReceiveDeleteMessagePayload */
    ReceiveDeleteMessagePayload: {
      /** Id */
      id: string;
      /**
       * Deletetype
       * @enum {string}
       */
      deleteType: 'deleteForEveryone' | 'both';
    };
    /** ReceiveEditMessagePayload */
    ReceiveEditMessagePayload: {
      /** Id */
      id: string;
      /** Text */
      text: string;
      /**
       * Editedat
       * @default null
       */
      editedAt: string | null;
    };
    /** ReceiveMessagePayload */
    ReceiveMessagePayload: {
      /** Id */
      id: string;
      /** Chatid */
      chatId: string;
      /** Text */
      text: string;
      /** Senderid */
      senderId: string;
      /** Createdat */
      createdAt: string;
      /** Servertimestamp */
      serverTimestamp: string;
      /** Isdeletedforeveryone */
      isDeletedForEveryone: boolean;
    };
    /** TypingBroadcastPayload */
    TypingBroadcastPayload: {
      /** Chatid */
      chatId: string;
      /** Userid */
      userId: string;
      /** Istyping */
      isTyping: boolean;
    };
    /** WsClientMessage */
    WsClientMessage: {
      /**
       * Event
       * @enum {string}
       */
      event:
        | 'SEND_MSG'
        | 'TYPING'
        | 'MSG_STATUS'
        | 'PRESENCE'
        | 'EDIT_MSG'
        | 'DELETE_MSG';
      /** Payload */
      payload:
        | components['schemas']['SendMessagePayload']
        | components['schemas']['TypingPayload']
        | components['schemas']['MessageStatusPayload']
        | components['schemas']['PresencePayload']
        | components['schemas']['EditMessagePayload']
        | components['schemas']['DeleteMessagePayload'];
      /**
       * Timestamp
       * @default null
       */
      timestamp: number | string | null;
    };
    /** WsServerMessage */
    WsServerMessage: {
      /**
       * Event
       * @enum {string}
       */
      event:
        | 'ACK_SEND_MSG'
        | 'RECEIVE_MSG'
        | 'TYPING'
        | 'MSG_STATUS'
        | 'PRESENCE'
        | 'ACK_EDIT_MSG'
        | 'RECEIVE_EDIT_MSG'
        | 'ACK_DELETE_MSG'
        | 'RECEIVE_DELETE_MSG'
        | 'ERROR';
      /** Payload */
      payload:
        | components['schemas']['AckSendMessagePayload']
        | components['schemas']['ReceiveMessagePayload']
        | components['schemas']['TypingBroadcastPayload']
        | components['schemas']['MessageStatusBroadcastPayload']
        | components['schemas']['PresenceBroadcastPayload']
        | components['schemas']['AckEditMessagePayload']
        | components['schemas']['ReceiveEditMessagePayload']
        | components['schemas']['AckDeleteMessagePayload']
        | components['schemas']['ReceiveDeleteMessagePayload']
        | components['schemas']['ErrorPayload'];
      /** Timestamp */
      timestamp: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
